# RGBY (refined)
PALETTE_ENV=11
PALETTE_SCOPE=13
PALETTE_PATH=12
PALETTE_SPECIAL=3
PALETTE_SUCCESS=2
PALETTE_ERROR=1
PALETTE_SUGGESTION=6
PALETTE_STRING=5
PALETTE_FG=252
PALETTE_BG=16
PALETTE_CURSOR=7
PALETTE_CONTRAST=dark
